DELETE FROM DEPARTAMENTO_TRA;
DELETE FROM ESTADO_PROD;
DELETE FROM TRABAJADOR;
DELETE FROM USUARIO;

DROP TABLE DEPARTAMENTO_TRA;
DROP TABLE TRABAJADOR;
DROP TABLE USUARIO;
DROP TABLE ESTADO_PROD;
DROP TABLE TIPO_PROD;
DROP TABLE PRODUCTO;
DROP TABLE SOLICITUD;
DROP TABLE ORDEN_DE_COMPRA;

CREATE TABLE DEPARTAMENTO_TRA (
IDDEPTRA NUMBER(6),
NOMBREDEPTRA VARCHAR2(100),
CONSTRAINT PK_IDDEPTRA PRIMARY KEY (IDDEPTRA)
);

CREATE TABLE TRABAJADOR (
NRUT NUMBER(8),
DVRUT VARCHAR2(1) NOT NULL,
PNOMBRE VARCHAR2(50) NOT NULL,
SNOMBRE VARCHAR2(50) NOT NULL,
APPATERNO VARCHAR2(50) NOT NULL,
APMATERNO VARCHAR2(50) NOT NULL,
DEPARTAMENTO NUMBER(6),
NACIMIENTO DATE,
CONSTRAINT PK_NRUT PRIMARY KEY (NRUT),
CONSTRAINT FK_IDDEPTRA FOREIGN KEY(DEPARTAMENTO)
REFERENCES DEPARTAMENTO_TRA(IDDEPTRA)
);

CREATE TABLE USUARIO (
IDUSER NUMBER(5),
NRUT NUMBER(8),
DVRUT VARCHAR2(1) NOT NULL,
USERNAME VARCHAR2 (50) NOT NULL,
TAGNAME VARCHAR2 (30) NOT NULL,
PASSWORDUS VARCHAR2(20) NOT NULL,
CORREOUS VARCHAR2 (150) NOT NULL,
CONSTRAINT PK_IDuser PRIMARY KEY (IDuser),
CONSTRAINT FK_NRUT FOREIGN KEY(NRUT)
REFERENCES TRABAJADOR(NRUT)
);


CREATE TABLE ESTADO_PROD (
IDESPROD NUMBER(5),
NOMBREEsProd VARCHAR2(100) NOT NULL,
CONSTRAINT PK_IDESPROD PRIMARY KEY (IDESPROD)
);

CREATE TABLE TIPO_PROD(
IDTIPPROD NUMBER(6),
NOMBRETIPPROD VARCHAR2(20) NOT NULL,
CONSTRAINT PK_IDTIPPROD PRIMARY KEY (IDTIPPROD)
);

CREATE TABLE PRODUCTO (
IDPROD NUMBER(6),
IDTIPPROD NUMBER(6),
NOMBREProd VARCHAR2(100) NOT NULL,
CONSTRAINT PK_IDPROD PRIMARY KEY (IDPROD),
CONSTRAINT FK_IDTIPPROD FOREIGN KEY(IDTIPPROD)
REFERENCES TIPO_PROD(IDTIPPROD)
);

CREATE TABLE SOLICITUD (
ID_SOLI NUMBER(6) PRIMARY KEY,
IDPROD NUMBER(6),
IDESPROD NUMBER(5),
STOCK NUMBER(3) NOT NULL,
COMENTARIOS VARCHAR2(500) NULL,
FECHASOLI DATE,
FOREIGN KEY(IDPROD) REFERENCES PRODUCTO(IDPROD),
FOREIGN KEY(IDESPROD) REFERENCES ESTADO_PROD(IDESPROD)
);

CREATE TABLE ORDEN_DE_COMPRA (
IDORDEN NUMBER(3),
IVAPOR NUMBER(3),
IVA NUMBER(4),
NETO NUMBER(6),
TOTAL NUMBER(7)
);

INSERT INTO DEPARTAMENTO_TRA VALUES(1, 'GERENCIA');
INSERT INTO DEPARTAMENTO_TRA VALUES(2, 'DISEÑO GRÁFICO');
INSERT INTO DEPARTAMENTO_TRA VALUES(3, 'MARKETING');
INSERT INTO DEPARTAMENTO_TRA VALUES(4, 'COMMUNITY MANAGER');
INSERT INTO DEPARTAMENTO_TRA VALUES(5, 'ADQUISICIONES');
INSERT INTO DEPARTAMENTO_TRA VALUES(6, 'BODEGA');
INSERT INTO DEPARTAMENTO_TRA VALUES(7, 'VENTAS');

INSERT INTO ESTADO_PROD VALUES(1, 'SOLICITADO');
INSERT INTO ESTADO_PROD VALUES(2, 'ASIGNADO');
INSERT INTO ESTADO_PROD VALUES(3, 'CONTRATANDO PROVEEDOR');
INSERT INTO ESTADO_PROD VALUES(4, 'EN CAMINO');
INSERT INTO ESTADO_PROD VALUES(5, 'RECIBIDO');
INSERT INTO ESTADO_PROD VALUES(6, 'EN ESPERA');
INSERT INTO ESTADO_PROD VALUES(7, 'CANCELADO');

SELECT IDDEPTRA as "ID DE ROL", NOMBREDEPTRA as "NOMBRE DEl TRABAJO" FROM DEPARTAMENTO_TRA ORDER BY IDDEPTRA;
SELECT IDESPROD as "ID DE ESTADO", NOMBREEsProd as "ESTADO DE PRODUCTO" FROM ESTADO_PROD ORDER BY IDESPROD;

INSERT INTO TRABAJADOR VALUES (22560650, 1, 'SARAY', 'ESPERANZA', 'PEÑAYLILLO', 'MONTECINOS', 1, '26/11/2007');
INSERT INTO USUARIO VALUES (1, 22560650, 1, 'SarayPey', 'Jefita Pey ?', 'SP.Diamona2', 's.penaylillomontecinos@liceorbl.cl');

SELECT NRUT ||'-'||DVRUT AS RUT,
        PNOMBRE ||' '|| SNOMBRE ||' '|| APPATERNO ||' '|| APMATERNO AS "NOMBRE COMPLETO",
        EXTRACT(YEAR FROM SYSDATE) - EXTRACT (YEAR FROM NACIMIENTO) ||' ('||NACIMIENTO||')' AS "EDAD",
        NOMBREDEPTRA AS DEPARTAMENTO
    FROM TRABAJADOR tra JOIN DEPARTAMENTO_TRA dep ON (tra.DEPARTAMENTO = dep.IDDEPTRA)
    ORDER BY IDDEPTRA;

SELECT NRUT ||'-'|| DVRUT AS RUT,
        PNOMBRE ||' '|| SNOMBRE ||' '|| APPATERNO ||' '|| APMATERNO AS "TRABAJADOR",
        EXTRACT(YEAR FROM SYSDATE) - EXTRACT (YEAR FROM NACIMIENTO) ||' ('||NACIMIENTO||')' AS "EDAD",
        TAGNAME ||'(@' || USERNAME ||')' AS "USUARIO",
        CORREOUS AS CORREO,
        PASSWORDUS AS "CONTRASEÑA",
        dt.NOMBREDEPTRA AS DEPARTAMENTO
    FROM USUARIO NATURAL JOIN TRABAJADOR tra
    LEFT JOIN DEPARTAMENTO_TRA dt ON (tra.DEPARTAMENTO = dt.IDDEPTRA)
    ORDER BY IDUSER;
